ADD_PRODUCT_INTEGRITY_ERROR = "Product already exists"
ADD_PRODUCT_NOT_EMPTY_NAME_ERROR = "Name can't be empty"
ADD_PRODUCT_NOT_EMPTY_PRICE_ERROR = "Price can't be empty"
ADD_PRODUCT_INVALID_PRICE_ERROR = "Price value is invalid"
ADD_PRODUCT_NOT_POSTIIVE_REAL_ERROR = "Price must be a positive real number"
ADD_PRODUCT_INVALID_CATEGORY_ERROR = "Category is invalid"